---
- name: Create lg workspace
  ansible.builtin.file:
    path: "{{ automation_root_dir }}/lg"
    state: directory
    owner: "{{ automation_user }}"
    group: nogroup
    mode: '0755'

- name: Copy lg proxy binary
  ansible.builtin.copy:
    src: lg-proxy
    dest: "{{ automation_root_dir }}/lg/lg-proxy"
    owner: root
    group: nogroup
    mode: '0755'
  notify: Restart lg-proxy

- name: Render lg proxy config
  ansible.builtin.template:
    src: proxy-config.json.j2
    dest: "{{ automation_root_dir }}/lg/proxy-config.json"
    owner: root
    group: nogroup
    mode: '0644'
  notify: Restart lg-proxy

- name: Setup lg-proxy systemd service
  ansible.builtin.template:
    src: lg-proxy.service.j2
    dest: /etc/systemd/system/lg-proxy.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart lg-proxy

- name: Enable and start lg-proxy service
  ansible.builtin.systemd:
    name: lg-proxy.service
    enabled: true
    state: started
    daemon_reload: true
