- name: Restart lg-server
  ansible.builtin.systemd:
    name: lg-server.service
    state: restarted
    daemon_reload: true

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
