---
wireguard_private_key_path: "/etc/wireguard/privatekey"

wireguard_allowed_ips:
  - 10.0.0.0/8
  - 172.20.0.0/14
  - 172.31.0.0/16
  - fd00::/8
  - fe80::/64
  - ff00::/8

wireguard_nodes_group: "nodes"
wireguard_interface_prefix: "node_"
wireguard_keepalive: 25
inter_node_lla_prefix: "fe80::1023:"
