---
wireguard_private_key_path: "/etc/wireguard/privatekey"
wireguard_public_key_path: "/etc/wireguard/publickey"

wireguard_allowed_ips:
  - 10.0.0.0/8
  - 172.20.0.0/14
  - 172.31.0.0/16
  - fd00::/8
  - fe80::/64
  - ff00::/8

inter_node_lla_prefix: "fe80::1023:"
