---
lg_proxy_shared_secret: "changeme-lg-proxy-secret"
lg_proxy_listen:
  - "[::]:40953"

lg_server_shared_secret: "{{ lg_proxy_shared_secret }}"
lg_server_listen:
  - "[::]:40954"
lg_server_endpoint: "http://lg-api.svc.moe"
lg_server_poll_idle_timeout: 180
