$ANSIBLE_VAULT;1.1;AES256
39646430303531393731373430623539636135373161343932393639323565656665356662643738
3331343030383833393531306635383130323638666531320a366131653931613363383335656362
66393065336133383939663966343462346332313836323664356264323638373636386637616364
3631316438643638610a383935363935336537373334326561343363366133386166623566326435
35356632313263646231396436663239336538353138353034653465633530636162323066646535
62656639623835623936623033616633376631323739306630326432313962626236313839323065
30643736636364313765663263613735636136363931323761323732386131303862313535643534
66626537613336376533613762663465653961316162373932613562316161333962643636643833
37393837343231643361653561656638376531383132336434643536623335356430353465383262
31613233623832346531626637343331303230353932623036623430373631633031373037653738
62643539646635666231336265343966666331633236626662326333376633656131353064383635
65303166386361383062643033623439336465366236333862656262366635383838326563383433
32373430613464633331383237653766656562663639663366363439626266333736
